-- Optional sample inventory; no demo users, passwords, loans or patient data.
-- All samples start available; existing codes are never overwritten.
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00092','Portable Ventilator','เครื่องช่วยหายใจชนิดเคลื่อนย้ายได้','Life Support','Hamilton Medical','T1','T1-8842-TH','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึก 4','ชั้น 4','Bay 2B','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00382','Infusion Pump','เครื่องให้สารละลายทางหลอดเลือดดำ','Infusion System','Terumo','TE-112','TRM-9912-B','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึกอุบัติเหตุ','ชั้น 1','ห้องหัตถการฉุกเฉิน 2','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00291','Patient Monitor','เครื่องตรวจวัดสัญญาณชีพข้างเตียง','Monitoring','Philips','IntelliVue MX800','MX-4401-K','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึก 3','ชั้น 3','เตียง 304','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00421','Syringe Pump','เครื่องควบคุมการให้ยาทางกระบอกฉีด','Infusion System','B. Braun','Perfusor Space','BBR-5531-S','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึกผู้ป่วยใน','ชั้น 5','ห้อง 510','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00124','Defibrillator','เครื่องกระตุกหัวใจด้วยไฟฟ้าแบบมีจอภาพ','Emergency & Defibrillator','Zoll Medical','R Series Plus','ZL-7721-ER','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึกอุบัติเหตุ','ชั้น 1','Red Zone 1','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00512','Anesthesia Workstation','เครื่องดมยาสลบพร้อมระบบช่วยหายใจ','Surgical & OR','Dräger','Fabius Plus XL','DRG-8819-OR','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึกศัลยกรรม','ชั้น 2','OR 2','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00633','Point-of-Care Ultrasound','เครื่องอัลตราซาวด์แบบพกพา','Diagnostic','GE Healthcare','Venue Go','GE-2294-US','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึกผู้ป่วยนอก','ชั้น 2','ห้อง 204','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00789','12-Lead ECG Machine','เครื่องตรวจคลื่นไฟฟ้าหัวใจ 12 ลีด','Diagnostic','Mindray','BeneHeart R12','MN-6641-EKG','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึกผู้ป่วยใน','ชั้น 3','ห้อง 302','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00445','Syringe Pump (Perfusor)','เครื่องควบคุมการให้ยาทางกระบอกฉีด','Infusion System','B. Braun','Perfusor Space 2','BBR-9901-ICU','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึก 4','ชั้น 2','ตู้คลัง MEU-2B','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
insert into public.equipment(code,name,name_th,category,brand,model,serial_number,department,location,building,floor,bay,status,notes) values ('EQ-00720','Emergency Defibrillator','เครื่องกระตุกหัวใจไฟฟ้าฉุกเฉิน','Emergency & Defibrillator','Philips','HeartStart XL+','PH-4421-AED','หน่วยเครื่องมือแพทย์กลาง','MEU ชั้น 2','ตึกอุบัติเหตุ','ชั้น 1','Red Zone 1','ready','ข้อมูลเครื่องมือตัวอย่าง') on conflict(code) do nothing;
